spring.application.name=fitness-tracker-service
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:mem:fitnesstrackerdb
#
#spring.security.user.name=user
#spring.security.user.password=password
logging.level.org.springframework.security=DEBUG

# Football API Configuration
football.api.url=https://sport-highlights-api.p.rapidapi.com
football.api.host=sport-highlights-api.p.rapidapi.com
football.api.key=05b40c52-e4b5-4e09-a107-dbaf15c978d2
